### ISSUE TITLE
model speed issue

### ISSUE THREAD

**Issue by jihwan722** [matlab-deep-learning/Pretrained-Yolov9-Network-For-Object-Detection#1]
Hello,

I have been using the YOLOv8 model you uploaded previously and it has been working well. Currently, I am performing real-time object detection on images received from the camera in a simulation program. I understand that the YOLOv9 model is supposed to be more lightweight and faster compared to YOLOv8. However, after replacing the yolov8x.mat file with yolov9t.mat, I noticed that the detection speed is actually slower with YOLOv9t. Considering the model size, I would expect YOLOv9t to be much faster. Is there anything specific I should consider when applying the YOLOv9 model?
The attached image shows the time taken for different YOLO versions when running the same scenario using the Simulink profiler. It can be seen that the YOLOv9t model takes more time compared to the YOLOv8x model.

Thank you.
![profiler_yolov8x](https://github.com/user-attachments/assets/d35fbc53-4712-4898-b48d-a6a96b91f121)
![profiler_yolov9t](https://github.com/user-attachments/assets/9a42acb9-fe1c-4989-9fdd-36b00ba33bc1)

**Comment by zuberkhan175** [comment]
Hi,

The speed difference exists due to more ONNX operators in the YOLOv9 model (since imported via ONNX) compared to YOLOv8.
We are willing to consider this as an enhancement in future.
